name: quoter
version: '5.0.22'
summary: Command line utility to pull stock and index quotes
description: |
  Quoter fetches online stock quotes and index data for easy display on
  the command line.  Quotes and index values are scrapped from a financial
  website.

  Quoter can also display daily trend which details daily highs, lows, and 
  close information. See the Snap Store screen shots for examples.

  Lastly, the source code and a more elaborate readme is available on 
  GitHub and the program help (execute with -h switch) will show more
  information.

  Quoter homepage is at https://github.com/frossm/quoter

grade: stable
confinement: strict
base: core22

title: Quoter
website: https://github.com/frossm/quoter
contact: quoter@fross.org
issues: https://github.com/frossm/quoter/issues
icon: graphics/PostIt-512x512.png
license: MIT

# Enable faszter LZO compression
compression: lzo

# Ignore useless library warnings
lint:
  ignore:
    - library


apps:
   quoter:
      command: quoter-wrapper
      plugs:
         - network
         - home

parts:
   wrapper:
      plugin: dump
      source: snap/local
      source-type: local
      
   library:
      plugin: maven
      source: https://github.com/frossm/library.git
      source-type: git
      source-tag: 'v2023.07.14'
      maven-parameters:
        - install

      build-packages:
        - maven
        - openjdk-11-jdk-headless

   quoter:
      plugin: maven
      source: https://github.com/frossm/quoter.git
      source-branch: master
      source-type: git
      after:
        - library

      build-packages:
        - maven
        - openjdk-11-jdk-headless

      stage-packages:
        - openjdk-11-jre-headless

      override-prime: |
         snapcraftctl prime
         rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
